name: CI

concurrency: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
      - run: npm ci
      - run: |
          npm run lint -w client
          npm run lint -w api
          npm run lint -w shared

  test-shared:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
      - run: npm ci
      - run: |
          cd shared
          npx prisma contract emit
      - run: npm run test -w shared
      - run: npm run typecheck -w shared

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
      - run: npm ci
      - run: |
          cd shared
          npx prisma contract emit
      - run: npm run test -w client
      - run: npm run typecheck -w client

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
      - run: npm ci
      - run: |
          cd shared
          npx prisma contract emit
      - run: npm run test -w api
      - run: npm run typecheck -w api

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
      - run: npm audit --audit-level=high
